# nginx-on-worker.yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx-on-worker
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
  nodeSelector:
    kubernetes.io/hostname: minikube-m02
