apiVersion: v1
kind: Pod
metadata:
  name: nginx-on-m03
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
  nodeSelector:
    kubernetes.io/hostname: minikube-m03
